baseURL = "/"

enableRobotsTXT = true
enableInlineShortcodes = true
# Will give values to .Lastmod etc.
enableGitInfo = true

# Language configuration
[languages]
[languages.en]
title = "Spinnaker"
description = "Spinnaker is an open source, multi-cloud continuous delivery platform for releasing software changes with high velocity and confidence."
languageName ="English"
# Weight used for sorting.
weight = 1

# Docsy is now a Go module. Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]
# Sept 2023 If I don't include module.imports.mounts entries, compilation breaks with a lot of "not found" - can't find shortcodes or refs
[module]
proxy = "direct"

  [module.hugoVersion]
  extended = true
  min = "0.110.0"

  [[module.imports]]
  path = "github.com/google/docsy"
  disable = false

    [[module.imports.mounts]]
    source = "assets"
    target = "assets"

    [[module.imports.mounts]]
    source = "node_modules/bootstrap"
    target = "assets/vendor/bootstrap"

    [[module.imports.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free"
    target = "assets/vendor/Font-Awesome"

    [[module.imports.mounts]]
    source = "i18n"
    target = "i18n"

    [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"

    [[module.imports.mounts]]
    source = "static"
    target = "static"

    [[module.imports.mounts]]
    source = "data"
    target = "data"

    [[module.imports.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

  [[module.imports]]
  path = "github.com/google/docsy/dependencies"
  disable = false

  [[module.mounts]]
  source = "content/en"
  target = "content"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Google Analytics configuration
# https://gohugo.io/templates/internal/#configure-google-analytics
# https://www.docsy.dev/docs/adding-content/feedback/#adding-analytics
googleAnalytics = "G-H0XE7ESBFR"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Highlighting config (copied from the docsy example site, tag v0.7.1)
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "dracula"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
          [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.tableOfContents]
          endLevel = 3
          ordered = false
          startLevel = 2
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "dracula"
    # these are defaults https://gohugo.io/getting-started/configuration-markup/#highlight
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    tabWidth = 4
    guessSyntax = true
    # Set guessSyntax to true if you want your chosen highlight style used for code blocks without a specified language



# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"






# Everything below this are Site Params
[params]
copyright = 'Copyright © 2020 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds.'
privacy_policy = "http://www.linuxfoundation.org/privacy"
terms_of_use = "http://www.linuxfoundation.org/terms"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "Latest"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://spinnaker.io/docs/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/spinnaker/spinnaker.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/spinnaker/spinnaker"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true
offlineSearchMaxResults = 50
offlineSearchSummaryLength = 200

#  Promo Banner variables
[params.promoBanner]
  show = true
  text = "Spinnaker Summit 2023 keynotes and talks now available!"
  ctaLink = "https://www.youtube.com/playlist?list=PLwV5P7PgiYTXpyqBXOFjm36k4nl7g6NXq"
  ctaText = "Browse Playlist"
  label = ""

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable= true
sidebar_cache_limit = 10
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
nav_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/spinnaker/spinnaker.io/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/spinnaker/spinnaker.io/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "http://github.com/spinnaker"
	icon = "fab fa-github"
  desc = "Spinnaker on Github"
[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/spinnakerteam/shared_invite/zt-7juwxmx0-nQ4Ud4pJcbuPykX3SXwQrg"
	icon = "fab fa-slack"
  desc = "Spinnaker Community on Slack"

[[params.links.developer]]
  name = "Twitter"
  url = "https://twitter.com/spinnakerio"
  icon = "fab fa-twitter"
  desc = "Spinnaker Twitter"

# Additional menu item out
[[menu.main]]
  name = "Blog"
  weight = 4
  url = "https://blog.spinnaker.io/"

[[menu.main]]
  name = "Docs"
  weight = 2
  url = "/docs/"

[[menu.main]]
  name = "Community"
  weight = 3
  url = "/docs/community/"
  
[[menu.main]]
  name = "GitHub"
  weight = 50
  url = "https://github.com/spinnaker"
  pre = "<i class='fab fa-github'></i>"
