[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --minify" 
functions = "./functions"

[context.production.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --minify --enableGitInfo" 

[context.split1.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.2"

[context.branch-deploy]
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/setup/*"
  to = "/docs/setup/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/guides/*"
  to = "/docs/guides/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/reference/*"
  to = "/docs/reference/:splat"
  status = 301
  force = false
  
