# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
# Default build settings
[build]
publish = "public"
command = "hugo --gc"
functions = "./functions"

[context.production.environment]
GO_VERSION = "1.18"
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"  
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc"

[context.split1.environment]
GO_VERSION = "1.18"
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
GO_VERSION = "1.18"
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
GO_VERSION = "1.18"
HUGO_VERSION = "0.110.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "public"
exclude =[
  './public/includes/',
  './public/categories/',
  './public/tags/',
  './public/favicons/',
  './public/404.html'
]
# set baseURL because we aren't configuring a custom domain in Netlify
# Although the above is called base URL this actually ends up being the hostname in the sitemap and as such trying to use a URL like http://example.com/en/ will results in http://example.com/
# https://github.com/netlify-labs/netlify-plugin-sitemap
baseUrl = "https://spinnaker.io/"

# append missing trailing slash to prettyURL
trailingSlash = true
changeFreq = "daily"
priority = 0.5

# headers  https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# https://cloud-armory.slack.com/archives/CH4RVCCTS/p1608572781420500
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
